### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by Omega2911** [GameCraftPE/SurvivalGames#1]
can you add nopvptask, remove block and change the command, please?

**Comment by Driesboy** [comment]
done

**Comment by Driesboy** [comment]
https://github.com/GameCraftPE/SurvivalGames/blob/master/SW/src/svile/sw/SWarena.php#L328

**Comment by Driesboy** [comment]
https://github.com/GameCraftPE/SurvivalGames/blob/master/SW/src/svile/sw/SWarena.php#L342
